"""Safe read/write support for local BBS configuration."""
from __future__ import annotations

from pathlib import Path
from typing import Any

from connector.config import Settings, reload_settings

ENV_PATH = Path('.env')

FIELDS = {
    'track_name':'BBS_TRACK_NAME','default_theme':'BBS_DEFAULT_THEME','app_host':'BBS_APP_HOST',
    'app_port':'BBS_APP_PORT','public_base_url':'BBS_PUBLIC_BASE_URL','sql_host':'BBS_SQL_HOST',
    'sql_instance':'BBS_SQL_INSTANCE','sql_port':'BBS_SQL_PORT','sql_database':'BBS_SQL_DATABASE',
    'sql_user':'BBS_SQL_USER','sql_password':'BBS_SQL_PASSWORD','sql_driver':'BBS_SQL_DRIVER',
    'sql_encrypt':'BBS_SQL_ENCRYPT','sql_trust_server_certificate':'BBS_SQL_TRUST_SERVER_CERTIFICATE',
    'sql_connect_timeout':'BBS_SQL_CONNECT_TIMEOUT','sql_query_timeout':'BBS_SQL_QUERY_TIMEOUT',
    'cors_origins':'BBS_CORS_ORIGINS','current_moto_state_file':'BBS_CURRENT_MOTO_STATE_FILE',
    'current_moto_default':'BBS_CURRENT_MOTO_DEFAULT','lineup_cache_file':'BBS_LINEUP_CACHE_FILE',
}

class ConfigurationService:
    def get_public(self, settings: Settings) -> dict[str, Any]:
        data = {key: getattr(settings,key) for key in FIELDS if key != 'sql_password'}
        data['sql_password_configured'] = bool(settings.sql_password)
        data['sql_password'] = ''
        data['restart_required_for'] = ['app_host','app_port','cors_origins']
        return data

    def save(self, values: dict[str, Any]) -> Settings:
        existing = self._read_env()
        current = Settings()
        for field, env_name in FIELDS.items():
            if field not in values:
                continue
            value = values[field]
            if field == 'sql_password' and (value is None or str(value) == ''):
                continue
            if field in {'app_port','sql_port','sql_connect_timeout','sql_query_timeout','current_moto_default'}:
                value = '' if value in (None,'') else str(int(value))
            elif field in {'sql_encrypt','sql_trust_server_certificate'}:
                value = 'true' if bool(value) else 'false'
            else:
                value = str(value).strip()
            existing[env_name] = value
        self._write_env(existing)
        reload_settings()
        from connector.dependencies import get_database
        get_database.cache_clear()
        return Settings()

    @staticmethod
    def _read_env() -> dict[str,str]:
        data: dict[str,str] = {}
        if ENV_PATH.exists():
            for raw in ENV_PATH.read_text(encoding='utf-8').splitlines():
                line=raw.strip()
                if not line or line.startswith('#') or '=' not in line: continue
                key,value=line.split('=',1); data[key.strip()]=value.strip()
        return data

    @staticmethod
    def _write_env(data: dict[str,str]) -> None:
        lines=['# BMX Broadcast Suite local configuration','# Generated by /configuration. Do not commit this file.']
        lines += [f'{key}={value}' for key,value in sorted(data.items())]
        ENV_PATH.write_text('\n'.join(lines)+'\n',encoding='utf-8')
