"""Guided creation of the read-only bbs_connector SQL login.

This runs privileged operations (CREATE LOGIN, ALTER ROLE) against a live
scoring database, so the guardrails matter more than the feature:

- Pre-flight checks REPORT problems; they never fix them. This module never
  restarts SQL Server, enables mixed-mode authentication, enables TCP/IP, or
  touches the firewall -- see run_preflight().
- The exact SQL that will run is generated by build_create_plan()/
  build_reset_password_plan() and shown to the operator before anything
  executes. apply_plan() only ever executes a Plan object this module
  itself produced -- there is no code path that runs client-supplied SQL
  text. See connector/routes/setup.py for how the plan is cached
  server-side between the "show me the SQL" and "run it" steps, precisely
  so the client never has to (and never can) hand back arbitrary SQL for
  execution.
- The password is generated here, shown once in the plan's SQL text (so an
  operator can copy it for their own DBA if they prefer to run this
  themselves), and never appears in any object this module returns after
  apply_plan() succeeds. Callers must never log a Plan's `sql` attribute.
- Success is reported by reconnecting as the new login and reading a real
  row -- see verify_login(). "The CREATE statements didn't error" is not
  treated as proof of anything on its own.

Every function here takes an already-open connection or an explicit
connect callable, never opens one from a hardcoded identity -- see
connector/routes/setup.py for why (BBS's own process identity may or may
not have SQL admin rights; the route layer decides what to do in each
case, this module only knows how to talk to a connection it's handed).
"""

from __future__ import annotations

import secrets
import socket
import string
import time
from dataclasses import dataclass
from typing import Any, Protocol

try:
    import winreg
except ImportError:  # pragma: no cover - non-Windows dev/test environments
    winreg = None  # type: ignore[assignment]

try:
    import pyodbc
except ImportError:  # pragma: no cover - enables tests without native ODBC
    pyodbc = None  # type: ignore[assignment]

LOGIN_NAME = "bbs_connector"
# A standard RaceManager install's SQL Server Express instance -- confirmed
# live. Offered as the pre-filled default; detect_local_sql_instances()
# below is the actual detection, this is just the fallback guess when
# detection finds nothing (e.g. running the wizard from a machine other
# than the SQL Server itself, where the registry key doesn't exist).
COMMON_RACEMANAGER_INSTANCE = "USABMX"
PASSWORD_LENGTH = 24
PASSWORD_SYMBOLS = "!@#$%^&*-_="


class SqlSetupError(RuntimeError):
    """Raised when a setup step cannot be completed."""


class SupportsCursor(Protocol):
    def cursor(self) -> Any: ...


def windows_auth_connection_string(
    *, host: str, instance: str, database: str, driver: str = "ODBC Driver 18 for SQL Server"
) -> str:
    server = f"{host}\\{instance}" if instance else host
    return (
        f"DRIVER={{{driver}}};SERVER={server};DATABASE={database};"
        "Trusted_Connection=yes;Encrypt=yes;TrustServerCertificate=yes;"
    )


def sql_auth_connection_string(
    *,
    host: str,
    instance: str,
    database: str,
    user: str,
    password: str,
    driver: str = "ODBC Driver 18 for SQL Server",
) -> str:
    server = f"{host}\\{instance}" if instance else host
    return (
        f"DRIVER={{{driver}}};SERVER={server};DATABASE={database};"
        f"UID={user};PWD={password};Encrypt=yes;TrustServerCertificate=yes;"
    )


def generate_password() -> str:
    """A password that satisfies SQL Server's default CHECK_POLICY complexity
    rule (at least 3 of: uppercase, lowercase, digit, symbol) regardless of
    what secrets.choice happens to pick -- never a default, never derived
    from anything guessable."""
    alphabet = string.ascii_letters + string.digits + PASSWORD_SYMBOLS
    while True:
        candidate = "".join(secrets.choice(alphabet) for _ in range(PASSWORD_LENGTH))
        classes_present = sum(
            (
                any(c.isupper() for c in candidate),
                any(c.islower() for c in candidate),
                any(c.isdigit() for c in candidate),
                any(c in PASSWORD_SYMBOLS for c in candidate),
            )
        )
        if classes_present >= 3:
            return candidate


def detect_local_sql_instances() -> list[str]:
    """Best-effort enumeration of SQL Server instance names installed on
    THIS machine, from the registry. Returns [] on anything other than a
    clean read (non-Windows, permission denied, key absent, no SQL Server
    installed locally) -- never raises. This only helps pre-fill the
    wizard's instance field; it is not required for the wizard to work
    against a remote or undetectable instance."""
    if winreg is None:
        return []
    try:
        with winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE,
            r"SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL",
        ) as key:
            names: list[str] = []
            index = 0
            while True:
                try:
                    name, _value, _type = winreg.EnumValue(key, index)
                except OSError:
                    break
                names.append(name)
                index += 1
            return names
    except OSError:
        return []


def connect(connection_string: str, *, timeout: float = 5.0) -> Any:
    """The one real pyodbc.connect() call in this module -- isolated here,
    like database/racemanager.py's _connect(), so every other function
    stays testable with a fake connection. Raises SqlSetupError with the
    real driver error message rather than letting a raw pyodbc.Error
    surface; never used to report anything other than "connection failed",
    never guessed at.
    """
    if pyodbc is None:
        raise SqlSetupError("pyodbc is not installed.")
    try:
        return pyodbc.connect(connection_string, timeout=timeout, autocommit=True)
    except pyodbc.Error as exc:
        raise SqlSetupError(str(exc)) from exc


def _probe_tcp(host: str, port: int, *, timeout: float = 2.0) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


@dataclass(frozen=True)
class PreflightReport:
    connected: bool
    connection_error: str | None
    server_version: str | None
    integrated_security_only: bool | None  # None = could not determine
    tcp_reachable: bool | None  # None = not checked (no port given)
    existing_login_present: bool
    blocking_issues: list[str]


def run_preflight(
    connection: SupportsCursor | None,
    *,
    connection_error: str | None = None,
    tcp_host: str | None = None,
    tcp_port: int | None = None,
) -> PreflightReport:
    """Reports what it finds; changes nothing. If `connection` is None (the
    caller couldn't open one), pass `connection_error` and this still
    returns a usable report with everything it can determine externally
    (currently just the TCP probe)."""
    blocking: list[str] = []
    tcp_reachable = _probe_tcp(tcp_host, tcp_port) if (tcp_host and tcp_port) else None
    if tcp_reachable is False:
        blocking.append(
            f"Could not reach {tcp_host}:{tcp_port} over TCP. BBS needs a TCP connection to "
            "this SQL Server for its own day-to-day use (not just this one-time Windows-"
            "authenticated setup step) -- verify TCP/IP is enabled for this instance in SQL "
            "Server Configuration Manager and that no firewall is blocking it. This wizard "
            "will not change either of those for you."
        )

    if connection is None:
        return PreflightReport(
            connected=False,
            connection_error=connection_error,
            server_version=None,
            integrated_security_only=None,
            tcp_reachable=tcp_reachable,
            existing_login_present=False,
            blocking_issues=blocking,
        )

    cursor = connection.cursor()
    cursor.execute("SELECT SERVERPROPERTY('IsIntegratedSecurityOnly') AS v, @@VERSION AS ver")
    row = cursor.fetchone()
    integrated_only = bool(row[0]) if row is not None and row[0] is not None else None
    version = str(row[1]) if row is not None and row[1] is not None else None

    cursor.execute("SELECT name FROM sys.sql_logins WHERE name = ?", (LOGIN_NAME,))
    existing_login_present = cursor.fetchone() is not None

    if integrated_only:
        blocking.append(
            "Mixed-mode authentication is OFF on this SQL Server "
            "(SERVERPROPERTY('IsIntegratedSecurityOnly') = 1) -- a SQL login cannot be "
            "created or used until it's turned on. That requires restarting the SQL Server "
            "service, which this wizard will not do for you and which must not happen while "
            "racing is in progress. Ask whoever administers this SQL Server to enable "
            "'SQL Server and Windows Authentication mode' (SSMS: right-click the server -> "
            "Properties -> Security), then restart the SQL Server service during a break."
        )

    return PreflightReport(
        connected=True,
        connection_error=None,
        server_version=version,
        integrated_security_only=integrated_only,
        tcp_reachable=tcp_reachable,
        existing_login_present=existing_login_present,
        blocking_issues=blocking,
    )


@dataclass(frozen=True)
class Plan:
    """A specific, already-generated set of SQL statements -- see module
    docstring for why apply_plan() only ever accepts one of these, never a
    client-supplied string."""

    kind: str  # "create" | "reset_password"
    sql: str  # contains the plaintext password -- never log this
    password: str  # never returned to the client after apply_plan() succeeds
    database: str


def build_create_plan(*, database: str) -> Plan:
    password = generate_password()
    escaped = password.replace("'", "''")
    sql = (
        f"CREATE LOGIN [{LOGIN_NAME}] WITH PASSWORD = N'{escaped}', "
        "CHECK_POLICY = ON, CHECK_EXPIRATION = OFF;\n"
        f"USE [{database}];\n"
        f"CREATE USER [{LOGIN_NAME}] FOR LOGIN [{LOGIN_NAME}];\n"
        f"ALTER ROLE db_datareader ADD MEMBER [{LOGIN_NAME}];"
    )
    return Plan(kind="create", sql=sql, password=password, database=database)


def build_reset_password_plan(*, database: str) -> Plan:
    password = generate_password()
    escaped = password.replace("'", "''")
    sql = f"ALTER LOGIN [{LOGIN_NAME}] WITH PASSWORD = N'{escaped}';"
    return Plan(kind="reset_password", sql=sql, password=password, database=database)


def build_cleanup_sql(*, database: str) -> str:
    """Read-only informational text -- offered to the operator so a track
    can undo this without calling anyone. Never executed by this module."""
    return (
        f"USE [{database}];\n"
        f"DROP USER IF EXISTS [{LOGIN_NAME}];\n"
        "USE [master];\n"
        f"DROP LOGIN [{LOGIN_NAME}];"
    )


def apply_plan(connection: SupportsCursor, plan: Plan) -> None:
    """Executes exactly the statements in `plan.sql` -- nothing else. Splits
    on ';' + newline since pyodbc's default driver does not support
    multi-statement batches with a USE in the middle reliably across all
    ODBC driver versions; each statement is executed in order on the same
    connection so USE takes effect for the statements that follow it."""
    cursor = connection.cursor()
    for statement in _split_statements(plan.sql):
        cursor.execute(statement)
    if hasattr(connection, "commit"):
        connection.commit()


def _split_statements(sql: str) -> list[str]:
    return [line.strip() for line in sql.split(";") if line.strip()]


@dataclass(frozen=True)
class CachedPlan:
    plan: Plan
    host: str
    instance: str
    database: str
    created_at: float


class PlanCache:
    """Server-side home for a Plan between "show me the SQL" and "run it" --
    see the module docstring. A plan is single-use (take() removes it) and
    expires after `ttl_seconds` even if never applied, so a stale browser
    tab from an earlier session can't replay an old plan (and its
    password) later.
    """

    def __init__(self, *, ttl_seconds: float = 300.0, clock: Any = time.monotonic) -> None:
        self._plans: dict[str, CachedPlan] = {}
        self._ttl_seconds = ttl_seconds
        self._clock = clock

    def store(self, plan: Plan, *, host: str, instance: str, database: str) -> str:
        self._prune()
        plan_id = secrets.token_urlsafe(24)
        self._plans[plan_id] = CachedPlan(
            plan=plan, host=host, instance=instance, database=database, created_at=self._clock()
        )
        return plan_id

    def take(self, plan_id: str) -> CachedPlan | None:
        """Single-use: removes the entry whether it's found, expired, or
        not -- an expired entry is dropped the moment it's looked at."""
        self._prune()
        return self._plans.pop(plan_id, None)

    def _prune(self) -> None:
        now = self._clock()
        expired = [
            pid for pid, cached in self._plans.items() if now - cached.created_at > self._ttl_seconds
        ]
        for pid in expired:
            self._plans.pop(pid, None)


def verify_login(connection: SupportsCursor) -> dict[str, Any]:
    """Reconnect as the new login (the caller opens `connection` using
    sql_auth_connection_string with the new credentials) and read one real
    row from Evt.Races -- proof the login works AND can actually read
    RaceManager data, not just that CREATE LOGIN didn't error.

    Raises SqlSetupError with a plain-language reason on any failure --
    never returns a fabricated success.
    """
    try:
        cursor = connection.cursor()
        cursor.execute("SELECT TOP 1 * FROM Evt.Races")
        row = cursor.fetchone()
    except Exception as exc:  # noqa: BLE001 - surfaced to the operator, not fatal to BBS
        raise SqlSetupError(f"Connected as {LOGIN_NAME}, but reading Evt.Races failed: {exc}") from exc
    return {
        "login": LOGIN_NAME,
        "read_a_row_from": "Evt.Races",
        "row_found": row is not None,
    }
