"""Guided creation of the read-only bbs_connector SQL login.

This runs privileged operations (CREATE LOGIN, ALTER ROLE) against a live
scoring database, so the guardrails matter more than the feature:

- The exact SQL that will run is generated by build_create_plan()/
  build_reset_password_plan()/build_offline_create_plan(). apply_plan()
  only ever executes a Plan object this module itself produced -- there
  is no code path that runs client-supplied SQL text.
- The password is generated here and never appears in any object this
  module returns after apply_plan() succeeds. Callers must never log a
  Plan's `sql` attribute.
- Success is reported by reconnecting as the new login and reading a real
  row -- see verify_login(). "The CREATE statements didn't error" is not
  treated as proof of anything on its own.

Every function here takes an already-open connection or an explicit
connect callable, never opens one from a hardcoded identity -- see
connector/routes/setup.py, which decides which credentials to connect
with in each case.

Three ways an operator gets `bbs_connector` set up (see
connector/routes/setup.py and docs/setup-wizard.md for the full picture):

1. Guided, with admin credentials (the primary path, works regardless of
   whether BBS and RaceManager's SQL Server share a computer): the
   operator types a SQL Server *administrator* login's username and
   password into the Setup page. BBS connects as that account over SQL
   authentication -- the only kind pyodbc can do with typed credentials;
   there is no way to hand it a Windows account and a password and have
   it authenticate as that arbitrary user -- checks it can actually
   manage logins (check_login_management_rights()), creates or resets
   bbs_connector, verifies it, saves it, and never persists, logs, or
   echoes the admin credentials anywhere. See connector/routes/setup.py's
   sql_admin_setup().
2. "I already have the password": the operator already has a working
   bbs_connector (or equivalent) login and just wants BBS to use it. No
   SQL runs at all -- see verify_login() and connector/routes/setup.py's
   sql_verify_and_store().
3. Copy the SQL for someone else to run (build_create_plan()/
   build_offline_create_plan()/build_reset_password_plan()/
   build_cleanup_sql()): the last-resort path for a track with its own
   DBA. Nothing here ever assumes the person running it is anyone in
   particular -- see docs/setup-wizard.md's troubleshooting section for
   the errors that happen when it's run as the wrong account.

login_name defaults to LOGIN_NAME ("bbs_connector") everywhere but is
overridable -- this exists purely so a throwaway login can be created,
verified, and dropped for testing without touching the login BBS itself
would actually use. See docs/setup-wizard.md's "Testing aids" section;
it is not meant to be exposed in the wizard's normal UI. Because it flows
straight into bracket-quoted SQL identifiers (CREATE LOGIN [name], etc.),
every function that builds SQL text from it validates it first -- see
validate_login_name(). This does NOT apply to the *admin* username in
sql_auth_connection_string()'s `user` parameter when it's an
administrator credential rather than a login being created -- that value
is never interpolated into SQL text, only into a connection string,
where _odbc_brace() is the correct and sufficient defense.
"""

from __future__ import annotations

import re
import secrets
import string
from dataclasses import dataclass
from typing import Any, Protocol

try:
    import winreg
except ImportError:  # pragma: no cover - non-Windows dev/test environments
    winreg = None  # type: ignore[assignment]

try:
    import pyodbc
except ImportError:  # pragma: no cover - enables tests without native ODBC
    pyodbc = None  # type: ignore[assignment]

LOGIN_NAME = "bbs_connector"
# A standard RaceManager install's SQL Server Express instance -- confirmed
# live. Offered as the pre-filled default; detect_local_sql_instances()
# below is the actual detection, this is just the fallback guess when
# detection finds nothing (e.g. running the wizard from a machine other
# than the SQL Server itself, where the registry key doesn't exist).
COMMON_RACEMANAGER_INSTANCE = "USABMX"
PASSWORD_LENGTH = 24
# Deliberately excludes ' " \ ; { } [ ] -- every character with special
# meaning to a T-SQL string literal, an ODBC connection string, or a
# bracket-quoted identifier. generate_password()'s output can therefore
# never itself be the thing that breaks a generated script or connection
# string; the escaping in build_create_plan() etc. and _odbc_brace()
# below exists for a hand-typed password, not because the generator
# needs it.
PASSWORD_SYMBOLS = "!@#$%^&*-_="

# SQL Server login/user names that BBS itself creates get interpolated
# into bracket-quoted identifiers (CREATE LOGIN [name]). There is no
# legitimate reason bbs_connector or a throwaway test login needs
# anything outside this -- see validate_login_name(). This is NOT applied
# to administrator usernames someone else's DBA already chose (see
# sql_auth_connection_string()).
_LOGIN_NAME_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")


class SqlSetupError(RuntimeError):
    """Raised when a setup step cannot be completed."""


class SupportsCursor(Protocol):
    def cursor(self) -> Any: ...


def validate_login_name(login_name: str) -> str:
    """Every function below that builds SQL text from a login_name calls
    this first. Rather than escape embedded brackets/semicolons (doubling
    a literal ']', as QUOTENAME does) and trust that's exhaustive, this
    restricts login_name to a safe, unquoted-identifier charset --
    letters, digits, underscore, starting with a letter or underscore. A
    name outside that is rejected with a clear SqlSetupError rather than
    silently truncated, escaped, or interpolated as-is. Returns the name
    unchanged on success, so callers can write
    `login_name = validate_login_name(login_name)`.
    """
    if not _LOGIN_NAME_PATTERN.match(login_name):
        raise SqlSetupError(
            f"'{login_name}' is not a usable login name -- use only letters, digits, and "
            "underscores, starting with a letter or underscore (up to 128 characters)."
        )
    return login_name


def _odbc_brace(value: str) -> str:
    """Brace-quotes an ODBC connection string value, doubling any literal
    '}' inside it -- the connection string spec's own escaping rule for a
    value that might contain ';', '{', '}', or other characters with
    special meaning to the parser. Applied unconditionally (not only when
    a special character is detected) so this doesn't depend on a
    character denylist being exhaustive; a plain alphanumeric value
    braces to itself with no functional difference. This is what makes it
    safe for `user` to be an arbitrary administrator username someone
    else's DBA chose, not just bbs_connector's own restricted-charset
    name, and for `password` to be anything an operator typed in.
    """
    return "{" + value.replace("}", "}}") + "}"


def sql_auth_connection_string(
    *,
    host: str,
    instance: str,
    database: str,
    user: str,
    password: str,
    driver: str = "ODBC Driver 18 for SQL Server",
) -> str:
    server = f"{host}\\{instance}" if instance else host
    return (
        f"DRIVER={{{driver}}};SERVER={server};DATABASE={database};"
        f"UID={_odbc_brace(user)};PWD={_odbc_brace(password)};Encrypt=yes;TrustServerCertificate=yes;"
    )


def generate_password() -> str:
    """A password that satisfies SQL Server's default CHECK_POLICY complexity
    rule (at least 3 of: uppercase, lowercase, digit, symbol) regardless of
    what secrets.choice happens to pick -- never a default, never derived
    from anything guessable."""
    alphabet = string.ascii_letters + string.digits + PASSWORD_SYMBOLS
    while True:
        candidate = "".join(secrets.choice(alphabet) for _ in range(PASSWORD_LENGTH))
        classes_present = sum(
            (
                any(c.isupper() for c in candidate),
                any(c.islower() for c in candidate),
                any(c.isdigit() for c in candidate),
                any(c in PASSWORD_SYMBOLS for c in candidate),
            )
        )
        if classes_present >= 3:
            return candidate


def detect_local_sql_instances() -> list[str]:
    """Best-effort enumeration of SQL Server instance names installed on
    THIS machine, from the registry. Returns [] on anything other than a
    clean read (non-Windows, permission denied, key absent, no SQL Server
    installed locally) -- never raises. This only helps pre-fill the
    wizard's instance field; it is not required for the wizard to work
    against a remote or undetectable instance."""
    if winreg is None:
        return []
    try:
        with winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE,
            r"SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL",
        ) as key:
            names: list[str] = []
            index = 0
            while True:
                try:
                    name, _value, _type = winreg.EnumValue(key, index)
                except OSError:
                    break
                names.append(name)
                index += 1
            return names
    except OSError:
        return []


def connect(connection_string: str, *, timeout: int = 5) -> Any:
    """The one real pyodbc.connect() call in this module -- isolated here,
    like database/racemanager.py's _connect(), so every other function
    stays testable with a fake connection. Raises SqlSetupError with the
    real driver error message rather than letting a raw pyodbc.Error
    surface; never used to report anything other than "connection failed",
    never guessed at.

    timeout must be an int, not a float -- pyodbc.connect()'s timeout
    kwarg maps straight to the ODBC SQL_ATTR_LOGIN_TIMEOUT attribute,
    which is a C long. Passing a float raises TypeError from inside
    pyodbc.connect() itself before any connection attempt happens (see
    database/racemanager.py's _connect(), which has always taken this as
    `connect_timeout: int`).
    """
    if pyodbc is None:
        raise SqlSetupError("pyodbc is not installed.")
    try:
        return pyodbc.connect(connection_string, timeout=timeout, autocommit=True)
    except pyodbc.Error as exc:
        raise SqlSetupError(str(exc)) from exc


def login_exists(connection: SupportsCursor, login_name: str) -> bool:
    """Whether a SQL login by this name already exists on the server --
    decides create vs reset. A plain, parameterized SELECT; changes
    nothing."""
    validate_login_name(login_name)
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sys.sql_logins WHERE name = ?", (login_name,))
    return cursor.fetchone() is not None


def check_login_management_rights(connection: SupportsCursor) -> bool:
    """Whether the connected account can create and alter SQL Server
    logins -- sysadmin, or the more narrowly scoped ALTER ANY LOGIN
    server permission. Checked before attempting anything else, so an
    administrator account that turns out not to have this gets a plain-
    language refusal (see connector/routes/setup.py's sql_admin_setup())
    instead of a raw SQL Server permission error (Msg 15151) partway
    through creating the login."""
    cursor = connection.cursor()
    cursor.execute(
        "SELECT CASE WHEN IS_SRVROLEMEMBER('sysadmin') = 1 THEN 1 "
        "WHEN HAS_PERMS_BY_NAME(NULL, NULL, 'ALTER ANY LOGIN') = 1 THEN 1 "
        "ELSE 0 END AS can_manage_logins"
    )
    row = cursor.fetchone()
    return bool(row[0]) if row is not None and row[0] is not None else False


@dataclass(frozen=True)
class Plan:
    """A specific, already-generated set of SQL statements -- see module
    docstring for why apply_plan() only ever accepts one of these, never a
    client-supplied string."""

    kind: str  # "create" | "reset_password" | "create_if_missing"
    sql: str  # contains the plaintext password -- never log this
    password: str  # never returned to the client after apply_plan() succeeds
    database: str


def build_create_plan(*, database: str, login_name: str = LOGIN_NAME) -> Plan:
    """For use only after login_exists() has already confirmed the login
    does not exist yet -- an unconditional CREATE LOGIN, matching what
    was just checked. For the "no live connection to check first" case,
    see build_offline_create_plan.
    """
    validate_login_name(login_name)
    password = generate_password()
    escaped = password.replace("'", "''")
    sql = (
        f"CREATE LOGIN [{login_name}] WITH PASSWORD = N'{escaped}', "
        "CHECK_POLICY = ON, CHECK_EXPIRATION = OFF;\n"
        f"USE [{database}];\n"
        f"CREATE USER [{login_name}] FOR LOGIN [{login_name}];\n"
        f"ALTER ROLE db_datareader ADD MEMBER [{login_name}];"
    )
    return Plan(kind="create", sql=sql, password=password, database=database)


def build_offline_create_plan(*, database: str, login_name: str = LOGIN_NAME) -> Plan:
    """For a DBA running this by hand, without BBS ever having checked
    whether the login already exists: guards every step with IF NOT
    EXISTS instead of assuming an answer -- the same pattern
    docs/racemanager-pc-setup.md's manual instructions have always used.
    Running this against a login that already exists creates nothing new
    and leaves its existing password untouched; it does not double as a
    password reset (see build_reset_password_plan for that)."""
    validate_login_name(login_name)
    password = generate_password()
    escaped = password.replace("'", "''")
    sql = (
        "USE [master];\n"
        f"IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'{login_name}')\n"
        "BEGIN\n"
        f"    CREATE LOGIN [{login_name}] WITH PASSWORD = N'{escaped}', "
        "CHECK_POLICY = ON, CHECK_EXPIRATION = OFF;\n"
        "END;\n"
        f"USE [{database}];\n"
        f"IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'{login_name}')\n"
        "BEGIN\n"
        f"    CREATE USER [{login_name}] FOR LOGIN [{login_name}];\n"
        "END;\n"
        f"IF IS_ROLEMEMBER(N'db_datareader', N'{login_name}') <> 1\n"
        "BEGIN\n"
        f"    ALTER ROLE db_datareader ADD MEMBER [{login_name}];\n"
        "END;"
    )
    return Plan(kind="create_if_missing", sql=sql, password=password, database=database)


def build_reset_password_plan(*, database: str, login_name: str = LOGIN_NAME) -> Plan:
    validate_login_name(login_name)
    password = generate_password()
    escaped = password.replace("'", "''")
    sql = f"ALTER LOGIN [{login_name}] WITH PASSWORD = N'{escaped}';"
    return Plan(kind="reset_password", sql=sql, password=password, database=database)


def build_cleanup_sql(*, database: str, login_name: str = LOGIN_NAME) -> str:
    """Read-only informational text -- offered to the operator so a track
    can undo this without calling anyone. Never executed by this module."""
    validate_login_name(login_name)
    return (
        f"USE [{database}];\n"
        f"DROP USER IF EXISTS [{login_name}];\n"
        "USE [master];\n"
        f"DROP LOGIN [{login_name}];"
    )


def apply_plan(connection: SupportsCursor, plan: Plan) -> None:
    """Executes exactly the statements in `plan.sql` -- nothing else. Splits
    on ';' + newline since pyodbc's default driver does not support
    multi-statement batches with a USE in the middle reliably across all
    ODBC driver versions; each statement is executed in order on the same
    connection so USE takes effect for the statements that follow it.

    That naive split would tear a BEGIN...END block (as used by
    build_offline_create_plan's IF NOT EXISTS guards) apart into invalid
    fragments, so plans of kind "create_if_missing" are refused here --
    they're copy/paste-only, meant to be run as a single batch by the
    operator's own tool (SSMS, sqlcmd), never through this function."""
    if plan.kind == "create_if_missing":
        raise SqlSetupError(
            "This plan is generated for manual/offline use and cannot be run automatically."
        )
    cursor = connection.cursor()
    for statement in _split_statements(plan.sql):
        cursor.execute(statement)
    if hasattr(connection, "commit"):
        connection.commit()


def _split_statements(sql: str) -> list[str]:
    return [line.strip() for line in sql.split(";") if line.strip()]


def verify_login(connection: SupportsCursor, *, login_name: str = LOGIN_NAME) -> dict[str, Any]:
    """Reconnect as the new login (the caller opens `connection` using
    sql_auth_connection_string with the new credentials) and read one real
    row from Evt.Races -- proof the login works AND can actually read
    RaceManager data, not just that CREATE LOGIN didn't error.

    Raises SqlSetupError with a plain-language reason on any failure --
    never returns a fabricated success.
    """
    try:
        cursor = connection.cursor()
        cursor.execute("SELECT TOP 1 * FROM Evt.Races")
        row = cursor.fetchone()
    except Exception as exc:  # noqa: BLE001 - surfaced to the operator, not fatal to BBS
        raise SqlSetupError(f"Connected as {login_name}, but reading Evt.Races failed: {exc}") from exc
    return {
        "login": login_name,
        "read_a_row_from": "Evt.Races",
        "row_found": row is not None,
    }
